### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: checkpoints/Qwen2-VL-7B-Instruct
adapter_name_or_path: checkpoints/critic_0108_negative/checkpoint-520
template: qwen2_vl
finetuning_type: lora

### export
export_dir: checkpoints/critic_0108_negative/merge-520
export_size: 2
export_device: cpu
export_legacy_format: false