model_name: autogui
output_name: ours_autoui_webshop_negative
agent_url: https://f3aac33cb9ce009c18.gradio.live

batch_size: 1
data_path: data/aitw_anns/0108/webshopping_val_policy.jsonl

image_save_dir: ./images/online_eval_images
appium_server_url: http://10.150.140.70:4724
max_steps: 15