model_name: autogui
output_name: autogui_webshop
agent_url: https://278d523de49f267277.gradio.live

batch_size: 1
data_path: data/aitw_anns/0108/webshopping_val_policy.jsonl

image_save_dir: ./images/online_eval_images
appium_server_url: http://10.150.140.70:4724
max_steps: 10