model_name: autogui
output_name: autogui
agent_url: https://32ced49942463076f5.gradio.live

batch_size: 1
data_path: data/aitw_anns/1218/general_val_policy.jsonl

image_save_dir: ./images/online_eval_images
appium_server_url: http://10.150.140.70:4724
max_steps: 10