run_name: 'digirl-general-online'
save_path: './checkpoints/rl-01018-negative'

# data 
data_path: './data/aitw_anns/0108/general_train_policy.jsonl'

# model setting
policy_lm: './checkpoints/Auto-UI-Base'
critic_lm: './checkpoints/critic_0108_negative/merge-520'

# hparams
epochs: 20
batch_size: 3
rollout_size: 16
grad_accum_steps: 32
warmup_iter: 0
lm_lr: 1e-6
max_grad_norm: 0.01
gamma: 0.5
do_sample: True
temperature: 1.0
tau: 0.01
max_new_tokens: 128

# evaluation
eval_only: False
eval_path: './data/aitw_anns/0108/general_val_policy.jsonl'