run_name: 'digirl-general-online'
save_path: 'checkpoints/seeclick_general/epoch_5'

# data 
data_path: './data/aitw_anns/0108/general_train_policy.jsonl'

# model setting
policy_lm: './checkpoints/Auto-UI-Base'
critic_lm: './checkpoints/critic_1218/merge-520'

# hparams
capacity: 2000  
epochs: 5  
batch_size: 4
rollout_size: 16  
grad_accum_steps: 32
warmup_iter: 0  
actor_epochs: 5 # 20
lm_lr: 1e-6
max_grad_norm: 0.01
gamma: 0.5
do_sample: True
temperature: 1.0
tau: 0.01 
max_new_tokens: 128

# evaluation
eval_only: True
test_task: aitw_general
eval_path: './data/aitw_anns/0108/general_val_policy.jsonl'