run_name: 'qwen2.5_general'
test_task: aitw_general 
model_name: rl_general_qwen2.5_epoch_1
save_path: './checkpoints/rl_general_qwen2.5/epoch_0'

# data 
data_path: './data/aitw_anns/0108/general_train_policy.jsonl'

# model setting
policy_lm: './checkpoints/Auto-UI-Base'
critic_lm: './checkpoints/critic_general_qwen2.5/merge-2780'

# hparams
epochs: 20
batch_size: 3
rollout_size: 16
grad_accum_steps: 32
warmup_iter: 0
lm_lr: 1e-6
max_grad_norm: 0.01
gamma: 0.5
do_sample: True
temperature: 1.0
tau: 0.01
max_new_tokens: 128

# evaluation
eval_only: False
eval_data: './data/aitw_anns/0108/general_val_policy.jsonl'