model_name: seeclick_general

# data 
eval_only: False
test_task: aitw_general # aitw_webshopping
train_data: './data/aitw_anns/0108/general_train_policy.jsonl'
eval_data: './data/aitw_anns/0108/general_val_policy.jsonl'

# model setting
qwen_path: './checkpoints/Qwen-VL-Chat'
policy_lm: './checkpoints/SeeClick-aitw'
critic_lm: './checkpoints/critic_1218/merge-520'

# hparams
epochs: 20
batch_size: 3
grad_accum_steps: 1