model_name: seeclick_general_v5_epoch_4

# data 
test_task: aitw_general 
train_data: './data/aitw_anns/0108/general_train_policy.jsonl'
eval_data: './data/aitw_anns/0108/general_val_policy.jsonl'

# model setting
policy_device: 'cuda:0'
critic_device: 'cuda:1'
qwen_path: './checkpoints/Qwen-VL-Chat'
policy_lm: './checkpoints/SeeClick-aitw'
save_model: './checkpoints/seeclick_general_v5/epoch_4'
# save_model: ''
critic_lm: './checkpoints/critic_general/merge-520'

# hparams
epochs: 20
batch_size: 1
grad_accum_steps: 32 # 32