model_name: seeclick_general_v4_epoch_8

# data 
test_task: aitw_general 
train_data: './data/aitw_anns/0108/general_train_policy.jsonl'
eval_data: './data/aitw_anns/0108/general_val_policy.jsonl'

# model setting
policy_device: 'cuda:0'
critic_device: 'cpu'
qwen_path: './checkpoints/Qwen-VL-Chat'
policy_lm: './checkpoints/SeeClick-aitw'
save_model: './checkpoints/seeclick_general_v4/epoch_8'
# save_model: ''
critic_lm: './checkpoints/critic_1218/merge-520'

# hparams
epochs: 20
batch_size: 3
grad_accum_steps: 32