model_name: autogui
agent_url: https://10fa314d7209849159.gradio.live

batch_size: 1
data_path: data/aitw_anns/1218/general_val_policy.jsonl

image_save_dir: ./images/online_eval_images
appium_server_url: http://10.150.140.70:4723
max_steps: 10