### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: checkpoints/Qwen2-VL-7B-Instruct
adapter_name_or_path: checkpoints/qwen2vl_aitw_label_1102_v2/checkpoint-1620
template: qwen2_vl
finetuning_type: lora

### export
export_dir: checkpoints/qwen2vl_aitw_label_1102_v2_step_1620_merge
export_size: 2
export_device: cpu
export_legacy_format: false